#visit: https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.9'
services:
  database:
    container_name: swyger-database
    image: coorise/swyger-nodejs-database:0.1.0
    build: #In case you did not publish on docker hub
      context: ./
      dockerfile: Dockerfile-dev
    env_file: .env
    #depends_on:
      #- mongodb
      #- base
      #- auth
    volumes:
      - ./:/home/server/swyger/database
      - ./node_modules:/home/server/swyger/database/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "0.0.0.0:${PORT}:${PORT}"
    command: npm run dev
    environment:
      - ACE_HOST=${ACE_HOST}